import { apiClient } from './apiClient';
import keycloak from '../config/keycloak';
import type { Artifact, ArtifactContent, SummaryStreamHandlers } from '../features/knowledge-base/types';
import { mockKnowledgeItems } from '../mocks/knowledgeBaseMocks';

// Toggle to false to use the real API contract once the backend is ready
const USE_MOCKS = import.meta.env.VITE_USE_MOCK_API !== 'false';

/**
 * Service responsible for managing the knowledge base unified artifacts.
 */
export const knowledgeService = {
    /**
     * Fetches all unified artifacts for a specific project.
     */
    async getUnifiedArtifacts(projectId: string): Promise<Artifact[]> {
        if (USE_MOCKS) {
            // Simulate network delay
            await new Promise(resolve => setTimeout(resolve, 300));
            return [...mockKnowledgeItems];
        }
        return await apiClient.fetch<Artifact[]>(`/api/v1/projects/${projectId}/artifacts`);
    },

    /**
     * Fetches the raw content of a specific artifact.
     */
    async getArtifactContent(projectId: string, artifactId: string): Promise<ArtifactContent> {
        if (USE_MOCKS) {
            await new Promise(resolve => setTimeout(resolve, 300));
            const item = mockKnowledgeItems.find(i => i.id === artifactId);
            if (!item) throw new Error("Artifact not found");
            return {
                content: `# ${item.title}\n\nThis is mocked raw content for the file.\n\n\`\`\`typescript\n// Example source code or file content\nexport function example() {\n  console.log("Hello from ${item.title}");\n}\n\`\`\`\n\n**Excerpt:** ${item.excerpt}\n\n*Last updated: ${item.lastUpdated}*`,
                mimeType: 'text/markdown'
            };
        }
        return await apiClient.fetch<ArtifactContent>(`/api/v1/projects/${projectId}/artifacts/${artifactId}/content`);
    },

    /**
     * Streams an AI summary of a specific artifact.
     */
    async summarizeArtifact(projectId: string, artifactId: string, handlers: SummaryStreamHandlers): Promise<void> {
        if (USE_MOCKS) {
            const item = mockKnowledgeItems.find(i => i.id === artifactId);
            const summaryText = item?.aiSummary || "Mock summary generated by local LLM.";
            
            let i = 0;
            const words = summaryText.split(' ');
            
            const timer = setInterval(() => {
                if (i < words.length) {
                    handlers.onToken(words[i] + ' ');
                    i++;
                } else {
                    clearInterval(timer);
                    handlers.onToken('\n\n*[Source Citation](#)*');
                    handlers.onDone();
                }
            }, 50); // 50ms per word simulates streaming
            return;
        }

        try {
            if (keycloak.authenticated) {
                await keycloak.updateToken(30);
            }
        } catch (error) {
            console.error('Failed to refresh Keycloak token for summary stream', error);
            void keycloak.login();
            return;
        }

        const res = await fetch(`/api/v1/projects/${projectId}/artifacts/${artifactId}/summary`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${keycloak.token}`
            }
        });

        if (!res.ok) {
            handlers.onError?.(new Error(`HTTP error! status: ${res.status}`));
            return;
        }

        const reader = res.body?.getReader();
        if (!reader) {
            throw new Error("No response stream");
        }

        const decoder = new TextDecoder();
        let buffer = "";

        while (true) {
            const { value, done } = await reader.read();
            if (done) break;

            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split("\n");
            buffer = lines.pop() ?? "";

            for (const line of lines) {
                if (!line.startsWith("data:")) continue;

                try {
                    const data = JSON.parse(line.slice(6)) as { type: string, content?: string, message?: string };
                    
                    if (data.type === 'token' && data.content) {
                        handlers.onToken(data.content);
                    } else if (data.type === 'done') {
                        handlers.onDone();
                        return;
                    } else if (data.type === 'error') {
                        handlers.onError?.(new Error(data.message || 'Stream error'));
                        return;
                    }
                } catch (e) {
                    console.error("Failed to parse SSE line", line, e);
                }
            }
        }
        
        // Fallback natural end
        handlers.onDone();
    }
};
